In [1]:
# Goal : Convert the dataset to a final dataset which will be used in making visuals and creating the report.
import pandas as pd

In [2]:
df = pd.read_csv("cleaned_dataset.csv")
df

     Categories  Amount spent
0      Shopping       3436.58
1        Travel      11671.89
2        Travel      36513.25
3      Shopping      24844.16
4           EMI      15811.51
..          ...           ...
995    Shopping      34447.35
996         EMI       6484.62
997      Travel      34519.58
998        Food      20946.16
999  Investment       6493.65

[1000 rows x 2 columns]

In [3]:
s = df["Categories"]
for i in s:
    s = set(s)

In [4]:
s

{'EMI', 'Food', 'Investment', 'Shopping', 'Travel'}

In [5]:
pivot_df = df.groupby('Categories')['Amount spent'].sum().reset_index()

In [6]:
pivot_df

   Categories  Amount spent
0         EMI    4439711.32
1        Food    5367643.75
2  Investment    5278014.54
3    Shopping    4490271.06
4      Travel    5677529.29

In [7]:
pivot_df.to_csv("Final_dataset.csv", index=False)