In [1]:
import pandas as pd

In [2]:
d1 = pd.read_csv("financial_transaction_test.csv")
d1

                                      Transaction_Text       Label
0    IKEA furniture shopping | Ref:37c9a05e | Amoun...    Shopping
1    MakeMyTrip hotel booking | Ref:7fb0c9d1 | Amou...      Travel
2    Uber ride payment | Ref:f3653a0a | Amount: INR...      Travel
3    Flipkart electronics purchase | Ref:ab027ce0 |...    Shopping
4    HDFC home loan EMI | Ref:44608adc | Amount: IN...         EMI
..                                                 ...         ...
995  Myntra clothing order | Ref:45daca7d | Amount:...    Shopping
996  SBI car loan EMI | Ref:613c7ae6 | Amount: INR ...         EMI
997  Ola cab fare | Ref:871b709f | Amount: INR 3451...      Travel
998  Zomato dinner bill | Ref:6fb63408 | Amount: IN...        Food
999  Zerodha stock purchase | Ref:0c980941 | Amount...  Investment

[1000 rows x 2 columns]

In [3]:
d2 = pd.read_csv("financial_transaction_train.csv")
d2

                                       Transaction_Text       Label
0     Swiggy order payment | Ref:0f8f77bb | Amount: ...        Food
1     Ola cab fare | Ref:8b98e0de | Amount: INR 7019.92      Travel
2     Dominos pizza order | Ref:2cfbbdd3 | Amount: I...        Food
3     Amazon online shopping | Ref:68e9a9f2 | Amount...    Shopping
4     Swiggy order payment | Ref:c49e5e14 | Amount: ...        Food
...                                                 ...         ...
9995  Reliance Digital purchase | Ref:68b04b14 | Amo...    Shopping
9996  Fixed deposit investment | Ref:0896493d | Amou...  Investment
9997  Amazon online shopping | Ref:a44d7f3e | Amount...    Shopping
9998  IRCTC train ticket booking | Ref:b2ea8952 | Am...      Travel
9999  IKEA furniture shopping | Ref:3a450697 | Amoun...    Shopping

[10000 rows x 2 columns]

In [ ]:
# Goals 
# 1. Clean up the dataset and create categories according to the shopping category labels.
# 2. Create one dataset containing total purchases of all the categories (will be used for making visuals).
# 3. Generate a report using AI on the datasets on the basis of defined constraints.